### PR TITLE
olsrd: migrate to using bison 3.7.1

### PR DESCRIPTION
**Pull request by ffontaine**
With the upgrade to bison 3.7.1 (openwrt commit 1cf842d) building
olsrd was failing.  Now, instead of the contents of header files
being directly inserted into the generated source files, they are
instead included with a #include directive.

The local.mk has, until now, done some magic with *-tmp files,
which is not longer necessary and even causes builds to fail.

```
src/cfgparser/oparse.c:265:10: fatal error: oparse.h-tmp: No such file or directory
 #include "oparse.h-tmp"
```

Suggested-by: Jo-Philipp Wich <jo@mein.io>
Signed-off-by: Perry Melange <isprotejesvalkata@gmail.com>
[Retrieved from:
https://github.com/openwrt-routing/packages/commit/5cc8e058850acbc22fe92c5e2b24863efc577971]
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

### CODE REVIEW

**Comment by decke** [comment]
I can confirm that this patch also works fine on Alpine Linux 3.13 with bison 3.7.4.

Thanks a lot for the patch!

**Comment by PolynomialDivision** [comment]
Looks good to me. Thanks! I will merge that.
